projectName: leonzalion.com Videos
fusionCompositions:
  - name: target
    metadata:
      width: 500
      height: 500

  - name: projection
    metadata:
      width: 1920
      height: 1080

  - name: radar
    metadata:
      width: 1000
      height: 1000
