name: Update Website Data


on:
  push:
    branches:
      - main

# on:
#   schedule:
#     # From 8AM EST to 10PM EST
#     - cron: "0 13-23,0-3 * * *"

jobs:
  update_stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16.x

      - name: Use pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.28.0

      - name: Install dependencies
        run: pnpm install --filter=./update-stats

      - name: Run update stats script
        run: pnpm update-stats
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.website-env.GH_ACCESS_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.website-env.WAKATIME_API_KEY }}
          RESCUETIME_API_KEY: ${{ secrets.website-env.RESCUETIME_API_KEY }}
          SOME_UNDEFINED_SECRET: ${{ secrets.monke }}
